-- create "checkpoints" table
CREATE TABLE "checkpoints" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_uuid" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "checkpoint_user_uuid" to table: "checkpoints"
CREATE INDEX "checkpoint_user_uuid" ON "checkpoints" ("user_uuid");
