-- reverse: create "user_roles" table
DROP TABLE "user_roles";
-- reverse: modify "users" table
ALTER TABLE "users" DROP CONSTRAINT "users_pkey", ADD COLUMN "name" character varying NULL, ADD COLUMN "discord_user_id" character varying NULL, ALTER COLUMN "salt" DROP NOT NULL, ALTER COLUMN "password" DROP NOT NULL, ADD COLUMN "username" character varying NULL, ALTER COLUMN "email" DROP NOT NULL, ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, ADD PRIMARY KEY ("id");
-- reverse: drop index "users_uuid_key" from table: "users"
CREATE UNIQUE INDEX "users_uuid_key" ON "users" ("uuid");
-- reverse: create index "roles_uuid_key" to table: "roles"
DROP INDEX "roles_uuid_key";
-- reverse: create index "roles_key_key" to table: "roles"
DROP INDEX "roles_key_key";
-- reverse: create index "role_uuid" to table: "roles"
DROP INDEX "role_uuid";
-- reverse: create index "role_key" to table: "roles"
DROP INDEX "role_key";
-- reverse: create "roles" table
DROP TABLE "roles";
