-- create "access_logs" table
CREATE TABLE "access_logs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "ip" character varying NOT NULL, "uri" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "accesslog_ip" to table: "access_logs"
CREATE INDEX "accesslog_ip" ON "access_logs" ("ip");
