{
 "title": "Web Analytics",
 "description": "Nginx access log analytics dashboard using Promtail and Loki v2+. Prometheus datasource is created from Loki service.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bot_user_agent_regex",
    "label": "Bot User Agent Regex",
    "query": ".*(bot|curl|crawler|worldping|python|witterbot).*"
   },
   { "name": "bot_http_referer_regex", "label": "Bot HTTP Referer Regex", "query": ".*varso\\.org.*" }
  ]
 },
 "panels": [
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [1h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [24h])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\", host=\"$host\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [2d])))"
    }
   ]
  },
  {
   "title": "Unique user visits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [7d])))"
    }
   ]
  },
  {
   "title": "New visitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri = `/favicon.ico` | __error__=`` [7d])))"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"$filename\", host=\"$host\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Visitor Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Unique user visits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [1d])))",
       "legendFormat": "Unique user visit count"
      }
     ]
    },
    {
     "title": "Unique user visits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [1d])))",
       "legendFormat": "Unique user visit count"
      }
     ]
    }
   ]
  },
  {
   "title": "Sources & Behaviours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top User IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | remote_addr != `127.0.0.1` | request_uri !~ `/wp-.*` | request_uri !~ `//wp-.*` | request_uri !~ `/*.wordfence.*` | request_uri !~ `/robots.txt` | request_uri !~ `/xmlrpc.php` | __error__=`` [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers (Without Bots)",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sum by(http_referer) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | http_referer !~ `$bot_http_referer_regex` | remote_addr != `127.0.0.1` | __error__=`` [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, sum by(request_uri) (count_over_time({container=\"varsoapi-nginx-1\"} | json | __error__=`` [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top Bot IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, sum by(remote_addr) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent =~ `$bot_user_agent_regex` | __error__=`` [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "topk(5, sum by(http_referer) (count_over_time({container=\"varsoapi-nginx-1\"} | json | http_user_agent !~ `$bot_user_agent_regex` | http_referer !~ `.*varso.org.*` | __error__=`` [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Requests & HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 28 },
   "targets": [
    {
     "expr": "topk(10, sum by(http_user_agent) (count_over_time({container=\"varsoapi-nginx-1\"} | json | __error__=`` [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({container=\"varsoapi-nginx-1\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({container=\"varsoapi-nginx-1\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate({container=\"varsoapi-nginx-1\"} | json | status >= 500 | __error__=`` [$__interval])) / sum(rate({container=\"varsoapi-nginx-1\"} | json | __error__=`` [$__interval])) / 100"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate({container=\"varsoapi-nginx-1\"} |= `Googlebot` [$__interval])) / sum(rate({container=\"varsoapi-nginx-1\"} != `Googlebot` [$__interval])) / 100"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (sum_over_time({container=\"varsoapi-nginx-1\"} | json | status = `200` | unwrap body_bytes_sent | __error__=`` [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{container=\"varsoapi-nginx-1\"} | json | line_format `request for {{.request_uri}} with HTTP status: {{.status}} from {{.remote_addr}} located {{.geoip_country_code}}`"
    }
   ]
  },
  {
   "title": "Request Statistics Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time({container=\"varsoapi-nginx-1\"} | json | unwrap request_time | __error__=`` [$__interval])",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by(host) (max_over_time({container=\"varsoapi-nginx-1\", container=\"varsoapi-nginx-1\"} | json | unwrap request_time | __error__=`` [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({container=\"varsoapi-nginx-1\"} | json | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (sum_over_time({container=\"varsoapi-nginx-1\"} | json | status = `200` | unwrap body_bytes_sent | __error__=`` [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}